data cleaning

1st import libraries

In [63]:
import pandas as pd

2nd load data

In [64]:
weather=pd.read_csv('nyc_weather.csv',na_values=['T'])
weather

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0.00,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0.00,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0.00,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0.00,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0.00,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0.00,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0.00,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0.00,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,NaN,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.80,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0.00,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,NaN,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0.00,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,NaN,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,NaN,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,NaN,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0.00,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0.00,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0.00,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,NaN,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0.00,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0.00,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,NaN,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0.00,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0.00,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0.00,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0.00,0,NaN,241

3rd Understanding the data structure of data

In [65]:
weather.shape

(31, 11)

In [66]:
weather.head(1)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0.0,5,NaN,281

In [67]:
weather.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

data type checking

In [68]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   EST                   31 non-null     object
 1   Temperature           31 non-null     int64
 2   DewPoint              31 non-null     int64
 3   Humidity              31 non-null     int64
 4   Sea Level PressureIn  31 non-null     float64
 5   VisibilityMiles       31 non-null     int64
 6   WindSpeedMPH          28 non-null     float64
 7   PrecipitationIn       24 non-null     float64
 8   CloudCover            31 non-null     int64
 9   Events                9 non-null      object
 10  WindDirDegrees        31 non-null     int64
dtypes: float64(3), int64(6), object(2)
memory usage: 2.8+ KB

In [69]:
weather.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,28.000000,24.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.892857,0.183750,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.871821,0.583317,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,0.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.500000,0.000000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,0.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,2.310000,8.000000,345.000000

4th handle missing data

In [70]:
weather.isnull().sum()

EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             3
PrecipitationIn          7
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64

In [71]:
weather.isnull().sum()/weather.shape[0]*100

EST                      0.000000
Temperature              0.000000
DewPoint                 0.000000
Humidity                 0.000000
Sea Level PressureIn     0.000000
VisibilityMiles          0.000000
WindSpeedMPH             9.677419
PrecipitationIn         22.580645
CloudCover               0.000000
Events                  70.967742
WindDirDegrees           0.000000
dtype: float64

In [72]:
weather['EST']=pd.to_datetime(weather['EST'])

In [73]:
type(weather['EST'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [74]:
weather.set_index('EST',inplace=True)

In [75]:
weather['WindSpeedMPH'].interpolate(method='time',inplace=True)

<ipython-input-75-136f08f182c7>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  weather['WindSpeedMPH'].interpolate(method='time',inplace=True)

In [76]:
weather['PrecipitationIn'].interpolate(method='time',inplace=True)

<ipython-input-76-685f097d459e>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  weather['PrecipitationIn'].interpolate(method='time',inplace=True)

In [77]:
weather[['WindSpeedMPH','PrecipitationIn']]

            WindSpeedMPH  PrecipitationIn
EST
2016-01-01      8.000000            0.000
2016-01-02      7.000000            0.000
2016-01-03      8.000000            0.000
2016-01-04      9.000000            0.000
2016-01-05      5.000000            0.000
2016-01-06      4.000000            0.000
2016-01-07      2.000000            0.000
2016-01-08      4.000000            0.000
2016-01-09      8.000000            0.900
2016-01-10      7.333333            1.800
2016-01-11      6.666667            0.000
2016-01-12      6.000000            0.000
2016-01-13     10.000000            0.000
2016-01-14      5.000000            0.080
2016-01-15      5.000000            0.160
2016-01-16      7.000000            0.240
2016-01-17      6.000000            0.050
2016-01-18     12.000000            0.025
2016-01-19     11.000000            0.000
2016-01-20      6.000000            0.000
2016-01-21      6.000000            0.000
2016-01-22     11.000000            0.010
2016-01-23     16.000000            2.310
2016-01-24      6.000000            1.155
2016-01-25      3.000000            0.000
2016-01-26      7.000000            0.000
2016-01-27      7.000000            0.000
2016-01-28      5.000000            0.000
2016-01-29      8.000000            0.000
2016-01-30      7.000000            0.000
2016-01-31      5.000000            0.000

In [78]:

weather['Events'].fillna('no event',inplace=True)

<ipython-input-78-cd4ec134f7bf>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  weather['Events'].fillna('no event',inplace=True)

In [79]:
weather.isnull().sum()

Temperature             0
DewPoint                0
Humidity                0
Sea Level PressureIn    0
VisibilityMiles         0
WindSpeedMPH            0
PrecipitationIn         0
CloudCover              0
Events                  0
WindDirDegrees          0
dtype: int64

In [80]:
print('Data is ready to Data Analysis---')

Data is ready to Data Analysis---

In [81]:
weather

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,
2016-01-01,38,23,52,30.03,10,8.000000,0.000,5,no event,281
2016-01-02,36,18,46,30.02,10,7.000000,0.000,3,no event,275
2016-01-03,40,21,47,29.86,10,8.000000,0.000,1,no event,277
2016-01-04,25,9,44,30.05,10,9.000000,0.000,3,no event,345
2016-01-05,20,-3,41,30.57,10,5.000000,0.000,0,no event,333
2016-01-06,33,4,35,30.50,10,4.000000,0.000,0,no event,259
2016-01-07,39,11,33,30.28,10,2.000000,0.000,3,no event,293
2016-01-08,39,29,64,30.20,10,4.000000,0.000,8,no event,79
2016-01-09,44,38,77,30.16,9,8.000000,0.900,8,Rain,76
2016-01-10,50,46,71,29.59,4,7.333333,1.800,7,Rain,109
2016-01-11,33,8,37,29.92,10,6.666667,0.000,1,no event,289
2016-01-12,35,15,53,29.85,10,6.000000,0.000,4,no event,235
2016-01-13,26,4,42,29.94,10,10.000000,0.000,0,no event,284
2016-01-14,30,12,47,29.95,10,5.000000,0.080,7,no event,266
2016-01-15,43,31,62,29.82,9,5.000000,0.160,2,no event,101
2016-01-16,47,37,70,29.52,8,7.000000,0.240,7,Rain,340
2016-01-17,36,23,66,29.78,8,6.000000,0.050,6,Fog-Snow,345
2016-01-18,25,6,53,29.83,9,12.000000,0.025,2,Snow,293
2016-01-19,22,3,42,30.03,10,11.000000,0.000,1,no event,293
2016-01-20,32,15,49,30.13,10,6.000000,0.000,2,no event,302
2016-01-21,31,11,45,30.15,10,6.000000,0.000,1,no event,312
2016-01-22,26,6,41,30.21,9,11.000000,0.010,3,Snow,34
2016-01-23,26,21,78,29.77,1,16.000000,2.310,8,Fog-Snow,42
2016-01-24,28,11,53,29.92,8,6.000000,1.155,3,Snow,327
2016-01-25,34,18,54,30.25,10,3.000000,0.000,2,no event,286
2016-01-26,43,29,56,30.03,10,7.000000,0.000,2,no event,244
2016-01-27,41,22,45,30.03,10,7.000000,0.000,3,Rain,311
2016-01-28,37,20,51,29.90,10,5.000000,0.000,1,no event,234
2016-01-29,36,21,50,29.58,10,8.000000,0.000,4,no event,298
2016-01-30,34,16,46,30.01,10,7.000000,0.000,0,no event,257
2016-01-31,46,28,52,29.90,10,5.000000,0.000,0,no event,241